[dependencies]
clap = {version = "4.5.53", features = ["derive"]}
thiserror = "2.0.17"
tokio = {version = "1.48.0", features = ["full"]}
tokio-stream = "0.1.17"

[package]
name = "nimi"
version = "0.1.0"
edition = "2024"
