[dependencies]
clap = {version = "4.5.53", features = ["derive"]}
console = "0.16.2"
rand = "0.9.2"
thiserror = "2.0.17"
tokio = {version = "1.48.0", features = ["full"]}

[package]
name = "nimi"
version = "0.1.0"
edition = "2024"
